window.CASEFILE={
reviewed:'6 October 2026',
sources:[
{id:'S1',name:'KTH · DD2391 course and Autumn 2026 offering',url:'https://www.kth.se/student/kurser/kurs/DD2391?l=en',scope:'Course identity, credits, cycle, selected offering and overlap restriction.'},
{id:'S2',name:'KTH · DD2395 course page',url:'https://www.kth.se/student/kurser/kurs/DD2395?l=en',scope:'Course identity, credits, cycle and overlap restriction. Offering details not established in this review.'},
{id:'S3',name:'LTU · A0002E course page',url:'https://www.ltu.se/en/education/course/a00/a0002e-introduction-to-information-security',scope:'Course identity, credits, bachelor’s level and displayed Autumn 2026 term. Detailed offering data not established.'},
{id:'S4',name:'Cybercampus · Introductory commissioned courses',url:'https://www.cybercampus.se/en/education/about-continuing-edu/introduktionskurser-1.1393693',scope:'Scope, language and format for two selected listings. Page displayed a last-changed date of 5 January 2026.'},
{id:'S5',name:'Cybercampus · Continuation commissioned courses',url:'https://www.cybercampus.se/en/education/about-continuing-edu/fortsattningskurser-1.1393694',scope:'Scope, language and format for two selected listings. Page displayed a last-changed date of 2 January 2026.'},
{id:'S6',name:'Cybercampus · Partners and members',url:'https://www.cybercampus.se/partnership/current-partners-and-members-1.1451809',scope:'Confirms KTH and Luleå University of Technology are listed as partners. This does not establish that every university course belongs in the Cybercampus catalogue.'}
],
records:[
{id:'R01',code:'DD2391',title:'Cybersecurity Overview',publisher:'KTH',type:'University course',source:'S1',fields:{scope:'7.5 ECTS',level:'Second cycle',language:'English · selected offering',format:'KTH Campus · daytime',timing:'24 Aug–23 Oct 2026 · 50% pace',audience:'Programme-student offering; eligibility restrictions apply'},caution:'Overlaps with DD2395 and DD2394; credits cannot be combined with either.',decision:'Retain a distinct course record with an overlap warning. Do not present this as an unrestricted professional-training offer.',next:'Confirm whether and how this programme course should be included in the Cybercampus catalogue.',checks:['D01','D02'],status:'Catalogue eligibility unconfirmed'},
{id:'R02',code:'DD2395',title:'Computer Security',publisher:'KTH',type:'University course',source:'S2',fields:{scope:'6 ECTS',level:'Second cycle',language:'Not established in reviewed material',format:'Not established in reviewed material',timing:'Specific offering not established',audience:'Specific eligibility requires offering review'},caution:'Overlapping content with DD2391; credits cannot be combined.',decision:'Preserve its own code and 6-credit scope. Do not copy DD2391’s language, dates or delivery details.',next:'Request the applicable offering details and confirm catalogue eligibility.',checks:['D01','D02'],status:'Offering details unconfirmed'},
{id:'R03',code:'A0002E',title:'Introduction to Information Security',publisher:'Luleå University of Technology',type:'University course',source:'S3',fields:{scope:'7.5 ECTS',level:'Bachelor’s level',language:'Not established in reviewed material',format:'Not established in reviewed material',timing:'Autumn 2026 displayed; dates unconfirmed',audience:'Entry and application route require confirmation'},caution:'An English webpage is not evidence of English-language teaching.',decision:'Standardise the decimal comma in 7,5 to 7.5. Leave teaching language and delivery unknown.',next:'Confirm language, delivery, dates and eligibility before creating a selectable offering.',checks:['D02','D03'],status:'Offering details unconfirmed'},
{id:'R04',code:'No public code identified',title:'Information security culture at work',publisher:'Cybercampus catalogue',type:'Commissioned training',source:'S4',fields:{scope:'40 study hours',level:'Introductory catalogue category',language:'Swedish',format:'Online',timing:'No scheduled instance established',audience:'No prior knowledge required'},caution:'Study hours do not establish a credit-bearing award.',decision:'Keep duration as 40 hours; do not assign ECTS. Record Cybercampus as publisher, not an assumed teaching provider.',next:'Confirm delivery partner, current availability and booking route.',checks:['D04','D06'],status:'Availability unconfirmed'},
{id:'R05',code:'No public code identified',title:'Mobile Malware Lab – Ransomware Demonstrator',publisher:'Cybercampus catalogue',type:'Commissioned training',source:'S4',fields:{scope:'Half-day workshop',level:'Introductory catalogue category',language:'English',format:'Not specified in the source field',timing:'On demand',audience:'Primarily non-technical staff; wider interest welcomed'},caution:'The location field is blank. On-demand delivery is not a scheduled course date.',decision:'Retain the stated half-day duration. Hold the delivery-format field for confirmation.',next:'Ask the catalogue coordinator to confirm format, delivery partner and booking lead time.',checks:['D05','D06'],status:'Delivery format unconfirmed'},
{id:'R06',code:'No public code identified',title:'Computer and network security',publisher:'Cybercampus catalogue',type:'Commissioned training',source:'S5',fields:{scope:'By agreement',level:'Continuation catalogue category',language:'English',format:'By agreement',timing:'No scheduled instance established',audience:'IT professionals; programming knowledge expected'},caution:'Negotiable scope and delivery are explicit source values, not accidental omissions.',decision:'Use a configurable-offer status. Do not replace “by agreement” with invented hours or a fixed format.',next:'Obtain agreed scope, format and schedule for a specific commission.',checks:['D05','D06'],status:'Commission-specific agreement needed'},
{id:'R07',code:'No public code identified',title:'Computer Network Security',publisher:'Cybercampus catalogue',type:'Commissioned training',source:'S5',fields:{scope:'7.5 credits / 200 hours as listed',level:'Continuation catalogue category',language:'Not specified in the source field',format:'Online',timing:'No scheduled instance established',audience:'Routing and switching knowledge expected'},caution:'Similar name to R06, but a different listing with different scope and delivery.',decision:'Keep a separate record pending identity confirmation. A similar title is insufficient to merge records.',next:'Confirm teaching language, provider and credit-award conditions; check whether R06 and R07 are related.',checks:['D05','D06','D07'],status:'Language and identity checks open'}
],
decisions:[
{id:'D01',priority:'P1',title:'Preserve the KTH credit-overlap restriction',records:['R01','R02'],source:['S1','S2'],observation:'The two course pages describe overlapping content and a restriction on combining credits.',action:'Keep separate records, attach a visible overlap warning and flag any proposed combined-credit pathway.',why:'A learner could otherwise be given an incorrect credit total.',done:'The restriction is recorded in both sample records.',open:'Confirm the intended catalogue audience before making either course selectable.'},
{id:'D02',priority:'P1',title:'Separate a university course from an available offer',records:['R01','R02','R03'],source:['S1','S2','S3','S6'],observation:'Partner status and a public course page do not establish availability through Cybercampus.',action:'Separate course identity from offering details and catalogue eligibility.',why:'Avoid implying open admission, commissioned availability or a confirmed start date.',done:'University courses are labelled as candidates for catalogue review.',open:'A responsible coordinator must confirm inclusion and access route.'},
{id:'D03',priority:'P1',title:'Do not infer teaching language from webpage language',records:['R03'],source:['S3'],observation:'The reviewed English LTU page does not establish the teaching language.',action:'Record the language as unconfirmed and ask for explicit offering-level evidence.',why:'The language of marketing information and the language of instruction are different fields.',done:'No English-teaching claim is made in the register.',open:'Obtain the applicable offering record or written confirmation.'},
{id:'D04',priority:'P2',title:'Keep study hours separate from awarded credits',records:['R04'],source:['S4'],observation:'This listing states a workload in hours.',action:'Preserve the source unit. Do not derive a credit award from a general workload equivalence.',why:'A workload calculation cannot establish that a provider awards academic credits.',done:'Scope is recorded as hours only.',open:'Ask about credit-bearing status only if needed for the intended catalogue use.'},
{id:'D05',priority:'P2',title:'Distinguish missing information from negotiable information',records:['R05','R06','R07'],source:['S4','S5'],observation:'Some fields are unspecified, while another listing explicitly allows agreement on scope and format.',action:'Use separate values for “not specified” and “by agreement”; ask targeted questions for each.',why:'A general missing-data flag would misrepresent a configurable commissioned offer.',done:'Each record retains its own information state.',open:'Resolve the relevant field or document a commission-specific agreement.'},
{id:'D06',priority:'P2',title:'Separate the catalogue publisher from the delivery provider',records:['R04','R05','R06','R07'],source:['S4','S5'],observation:'The selected listings are published in Cybercampus’s catalogue; provider ownership was not established here.',action:'Leave delivery provider unconfirmed rather than assign a university by inference.',why:'Clear ownership is needed for enquiries, corrections and future updates.',done:'The register identifies the publisher explicitly.',open:'Coordinator to route each enquiry to the responsible provider.'},
{id:'D07',priority:'P2',title:'Review similar titles without silently merging them',records:['R06','R07'],source:['S5'],observation:'Two network-security listings have similar names but different scope and format.',action:'Keep both records with a possible-relationship flag; ask for identifiers and provider confirmation.',why:'A title-only deduplication could erase a distinct offer.',done:'Separate IDs and source sections are retained.',open:'Confirm whether the relationship is distinct, equivalent or superseded.'}
],
actions:[
{id:'A01',priority:'P1',owner:'Dania · proposed preparer',route:'Cybercampus education coordinator',records:['R01','R02','R03'],when:'Day 1 · before catalogue inclusion',reason:'Resolve the scope decision before spending time polishing ineligible entries.',ask:'Should programme courses from partner universities be included in the intended catalogue, or is this collection limited to commissioned training? What eligibility and application fields are required?',evidence:'Written scope decision and named approver',status:'Draft prepared'},
{id:'A02',priority:'P1',owner:'Dania · proposed preparer',route:'KTH course administration · coordinator to confirm contact',records:['R01','R02'],when:'Day 1 · after A01 if included',reason:'Protect the credit restriction and establish the correct offering.',ask:'Please confirm the applicable offering, access route, teaching language and delivery format for DD2395, and the intended audience for DD2391. I have preserved the published credit-overlap restriction.',evidence:'Offering URL or written confirmation',status:'Draft prepared'},
{id:'A03',priority:'P1',owner:'Dania · proposed preparer',route:'LTU course administration · coordinator to confirm contact',records:['R03'],when:'Day 1 · after A01 if included',reason:'The page alone does not answer key enrolment questions.',ask:'For A0002E, could you confirm teaching language, delivery format, exact dates and the relevant application or eligibility route for the intended offering?',evidence:'Offering URL or written confirmation',status:'Draft prepared'},
{id:'A04',priority:'P2',owner:'Dania · proposed preparer',route:'Cybercampus catalogue coordinator',records:['R04','R05','R06','R07'],when:'Day 1 · consolidate into one enquiry',reason:'A single structured request avoids repetitive messages and identifies provider ownership.',ask:'Please confirm delivery-provider ownership and availability for these four listings; delivery format for R05; teaching language and credit-award conditions for R07; and whether R06 and R07 are distinct offers. Keep R06 scope and format as “by agreement” until commissioned.',evidence:'Provider mapping and answers linked to record IDs',status:'Draft prepared'},
{id:'A05',priority:'P2',owner:'Dania · proposed preparer',route:'Designated catalogue approver',records:['R01','R02','R03','R04','R05','R06','R07'],when:'Day 3 · review checkpoint',reason:'Unanswered items remain visible; no silent publication.',ask:'Review corrected fields against the evidence, approve eligible entries and keep unresolved entries on hold. Agree a follow-up date for outstanding replies.',evidence:'Dated approval or explicit hold with next owner',status:'Planned'}
]
};
